chemelli74/aioamazondevices

- .gitignore
Adding ignore support for `.idea/` which covers pycharm
> feat: Add gitignore information for pycharm

- src/aioamazondevices/api.py
Adding updated output functionality
> feat: modify output function

- .pre-commit-config.yaml
I'd rather use the rust version ... but its not my repo :)
> Adding commitlint into pre-commit

- src/aioamazondevices/api.py
- src/aioamazondevices/const.py
> fix: allow different openid.assoc_handle by country

- ruff.toml
> chore: update ruff target version

- src/aioamazondevices/api.py
> fix: improve aiohttp support

- CHANGELOG.md
- pyproject.toml
- src/aioamazondevices/__init__.py
- src/aioamazondevices/const.py
> fix: add missing models

- library_test.py
- **save_raw_data**: now is a `bool`
- **arguments**: merge data from config and from CLI instead of overwriting
- **parent** path: check and create before saving a file
- **devices**: alert if no devices are found
- **cluster_device_name**: if none specified, use `single_device_name` for the test
> test: improve library_test script

- CHANGELOG.md
- pyproject.toml
- src/aioamazondevices/__init__.py
- src/aioamazondevices/const.py
- Fix #197
- Fix #198
- Fix #210
> fix: add more models

- CHANGELOG.md
- pyproject.toml
- src/aioamazondevices/__init__.py
- src/aioamazondevices/api.py
- src/aioamazondevices/const.py
Replace #191 with a proper and tested fix.
> fix: openid.assoc_handle for UK accounts

- src/aioamazondevices/const.py
- Fixes #216
- Fixes #218
- Fixes #219
> fix: add more device models

- CHANGELOG.md
- pyproject.toml
- src/aioamazondevices/__init__.py
- src/aioamazondevices/api.py
- src/aioamazondevices/const.py
- Fixes #241 
- Fixes https://github.com/home-assistant/core/issues/146552
> fix: multibyte characters encoding

- scripts/sort_DEVICE_TYPE_TO_MODEL.py
- src/aioamazondevices/const.py
- Fixes #238 
- Fixes #243
- Fixes #245
- Fixes #247
- Fixes #254
> fix: update models list

- src/aioamazondevices/const.py
Update User-Agent (as per https://github.com/home-assistant/core/issues/146784#issuecomment-2974813319) 
hopefully will resolve 429 response in https://github.com/chemelli74/aioamazondevices/issues/272
> fix: update User-Agent

- src/aioamazondevices/const.py
> fix: add Argentina and Austria settings

- src/aioamazondevices/api.py
move where devices get ignored earlier to avoid KeyErrors for incompatible devices
> fix: ignore devices earlier

- src/aioamazondevices/api.py
> fix: inspect sensors for old devices

- src/aioamazondevices/api.py
Resolves https://github.com/chemelli74/aioamazondevices/issues/354
missing `await` on three calls
> chore: missing awaits

- CHANGELOG.md
- pyproject.toml
- src/aioamazondevices/__init__.py
- src/aioamazondevices/const.py
Add details for Norway and South Africa
> fix: add norway and south africa details

- CHANGELOG.md
- pyproject.toml
- src/aioamazondevices/__init__.py
- src/aioamazondevices/api.py
- src/aioamazondevices/const.py
> feat: queues API calls to avoid hitting the limit

- library_test.py
remove invalid defaults for argparse store_true
> test: remove wrong default for store_true

- CHANGELOG.md
- pyproject.toml
- src/aioamazondevices/__init__.py
- src/aioamazondevices/const.py
- Fixes #253
- Fixes #257 
- Fixes #269
- Fixes #326
- Fixes #327
- Fixes #345
- Fixes #374
- Fixes #391
- Fixes #405 
- Fixes #406
- Fixes #408
- Fixes #409
> fix: add model model details

- README.md
- library_test.py
- src/aioamazondevices/api.py
This adds the ability to launch skills
> feat: add ability to launch skills

- src/aioamazondevices/const.py
I have tested it with my polish account.
> fix: add proper configuration for Poland

- CHANGELOG.md
- pyproject.toml
- src/aioamazondevices/__init__.py
- src/aioamazondevices/const.py
- Fixes #426 
- Fixes #429
- Fixes #430
- Fixed #435
- Fixes #437 
- Fixes #447
> fix: add new models

- src/aioamazondevices/api.py
Was left in after merge by mistake
> refactor: remove redundant code
